project 'lightrail.xcodeproj/'

# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'lightrail' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for lightrail
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
  ]
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'RCTMapboxGL', :path => '../node_modules/react-native-mapbox-gl/ios'
  pod 'Firebase/Core'
end
